opt_in_rules:
  - empty_count
  - empty_string
excluded:
  - v1
  - Carthage
  - Pods
force_cast: warning
force_try:
  severity: warning
line_length: 
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 1000
  error: 1500
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - url
    - art
    - URL
    - app
    - lhs
    - rhs
    - key
reporter: "xcode"
